import { navbar } from "vuepress-theme-hope";

export default navbar([
  { text: "首页", icon: "house", link: "/" },
  {
    text: "博文",
    icon: "pen-to-square",
    prefix: "/posts/",
    children: [
      {
        text: "云原生与 K8s",
        icon: "docker",
        prefix: "tech/",
        children: [
          { text: "Kubernetes 核心概念", link: "kubernetes-concepts" },
          { text: "云原生生态全景", link: "cloud-native-cncf" },
          { text: "K8s 生产运维实践", link: "kubernetes-operations" },
          { text: "K8s 版本演进解读", link: "kubernetes-version-evolution" },
          { text: "平台工程", link: "platform-engineering" },
        ],
      },
      {
        text: "数据库",
        icon: "database",
        prefix: "tech/",
        children: [
          { text: "PostgreSQL 与 MongoDB 运维", link: "database-postgresql-mongodb" },
        ],
      },
      {
        text: "中间件",
        icon: "cubes",
        prefix: "tech/",
        children: [
          { text: "Redis 运维与排查", link: "middleware-redis" },
          { text: "Kafka 与 ZooKeeper 迁移", link: "middleware-kafka-zookeeper" },
          { text: "etcd 运维与故障排查", link: "middleware-etcd" },
        ],
      },
      {
        text: "存储与分析",
        icon: "chart-column",
        prefix: "tech/",
        children: [
          { text: "MinIO 与 ClickHouse 运维", link: "storage-minio-clickhouse" },
        ],
      },
      {
        text: "Golang 入门",
        icon: "code",
        prefix: "tech/",
        children: [
          { text: "环境搭建与基础语法", link: "golang-basics" },
          { text: "数据类型与错误处理", link: "golang-datatypes-control" },
          { text: "结构体、方法与接口", link: "golang-struct-interface" },
          { text: "并发编程实战", link: "golang-concurrency" },
          { text: "标准库与项目实战", link: "golang-stdlib-project" },
        ],
      },
      {
        text: "SRE 运维开发",
        icon: "gauge-high",
        prefix: "tech/",
        children: [
          { text: "SLI/SLO/SLA 体系", link: "sre-fundamentals" },
          { text: "CLI 工具开发", link: "sre-go-cli-tools" },
          { text: "Go 操作 K8s", link: "sre-go-kubernetes" },
          { text: "Prometheus Exporter", link: "sre-prometheus-exporter" },
          { text: "故障管理与 Runbook", link: "sre-incident-runbook" },
        ],
      },
      {
        text: "其他技术",
        icon: "wrench",
        prefix: "tech/",
        children: [
          { text: "VuePress 搭建博客", link: "vuepress-blog" },
          { text: "Cloudflare Pages 部署", link: "cloudflare-deploy" },
          { text: "Git 常用命令", link: "git-commands" },
        ],
      },
      {
        text: "生活",
        icon: "mug-hot",
        prefix: "life/",
        children: [
          { text: "2026 初夏", link: "early-summer-2026" },
          { text: "读书笔记：原则", link: "reading-principles" },
        ],
      },
      {
        text: "笔记",
        icon: "notebook",
        prefix: "notes/",
        children: [
          { text: "Linux 常用技巧", link: "linux-tips" },
        ],
      },
    ],
  },
  {
    text: "AI Wiki",
    icon: "brain",
    prefix: "/posts/wiki/",
    children: [
      {
        text: "概念",
        icon: "lightbulb",
        prefix: "concepts/",
        children: [
          { text: "MCP", link: "model-context-protocol" },
          { text: "Transformer", link: "transformer-architecture" },
          { text: "RAG", link: "retrieval-augmented-generation" },
          { text: "Embedding", link: "embedding" },
          { text: "思维链", link: "chain-of-thought" },
          { text: "Prompt Engineering", link: "prompt-engineering" },
          { text: "Agentic Coding", link: "agentic-coding" },
          { text: "Function Calling", link: "function-calling" },
          { text: "微调", link: "fine-tuning" },
          { text: "Tokenization", link: "tokenization" },
          { text: "向量数据库", link: "vector-database" },
          { text: "知识图谱", link: "knowledge-graph" },
          { text: "注意力机制", link: "attention-mechanism" },
          { text: "语义搜索", link: "semantic-search" },
          { text: "Constitutional AI", link: "constitutional-ai" },
          { text: "LLM 训练流程", link: "llm-training-pipeline" },
        ],
      },
      {
        text: "主题",
        icon: "folder-open",
        prefix: "topics/",
        children: [
          { text: "机器学习", link: "machine-learning" },
          { text: "深度学习", link: "deep-learning" },
          { text: "自然语言处理", link: "natural-language-processing" },
          { text: "计算机视觉", link: "computer-vision" },
          { text: "AI Agents", link: "ai-agents" },
          { text: "软件工程", link: "software-engineering" },
          { text: "DevOps", link: "devops" },
          { text: "Web 开发", link: "web-development" },
          { text: "开源", link: "open-source" },
          { text: "知识管理", link: "knowledge-management" },
        ],
      },
      {
        text: "对比",
        icon: "code-compare",
        prefix: "comparisons/",
        children: [
          { text: "GPT vs Claude vs Gemini", link: "gpt-vs-claude-vs-gemini" },
          { text: "VS Code vs Cursor vs Windsurf", link: "vscode-vs-cursor-vs-windsurf" },
          { text: "Obsidian vs Notion vs Logseq", link: "obsidian-vs-notion-vs-logseq" },
          { text: "RAG vs Compiled Wiki", link: "rag-vs-compiled-wiki" },
          { text: "Python vs JS vs Go", link: "python-vs-javascript-vs-go" },
          { text: "Docker vs Kubernetes", link: "docker-vs-kubernetes" },
        ],
      },
      {
        text: "公司人物",
        icon: "building",
        prefix: "entities/",
        children: [
          { text: "OpenAI", link: "openai" },
          { text: "Anthropic", link: "anthropic" },
          { text: "Google DeepMind", link: "google-deepmind" },
          { text: "Meta AI", link: "meta-ai" },
          { text: "Hugging Face", link: "hugging-face" },
          { text: "Claude", link: "claude" },
          { text: "GPT", link: "gpt" },
          { text: "Cursor", link: "cursor" },
          { text: "GitHub Copilot", link: "github-copilot" },
          { text: "Ollama", link: "ollama" },
          { text: "Perplexity", link: "perplexity" },
          { text: "Vercel", link: "vercel" },
          { text: "Obsidian", link: "obsidian" },
          { text: "Sam Altman", link: "sam-altman" },
          { text: "Andrej Karpathy", link: "andrej-karpathy" },
        ],
      },
      {
        text: "指南",
        icon: "book-open",
        prefix: "guides/",
        children: [
          { text: "构建 RAG 系统", link: "how-to-build-rag-system" },
          { text: "微调 LLM", link: "how-to-fine-tune-llm" },
          { text: "构建 AI Agent", link: "how-to-build-ai-agent" },
          { text: "写好 Prompt", link: "how-to-write-effective-prompts" },
          { text: "使用 Obsidian", link: "how-to-use-obsidian" },
          { text: "升级 Dify RAG", link: "how-to-upgrade-dify-rag-workflow" },
          { text: "构建 LLM Wiki", link: "how-to-build-llm-wiki" },
        ],
      },
      {
        text: "综合分析",
        icon: "chart-line",
        prefix: "synthesis/",
        children: [
          { text: "2026 AI 状态", link: "state-of-ai-2026" },
          { text: "LLM 演进", link: "evolution-of-llm" },
          { text: "编程的未来", link: "future-of-programming" },
          { text: "AI 安全全景", link: "ai-safety-landscape" },
          { text: "LLM 应用模式", link: "llm-application-patterns" },
          { text: "开源 AI 生态", link: "open-source-ai-ecosystem" },
        ],
      },
    ],
  },
  {
    text: "功能演示",
    icon: "laptop-code",
    prefix: "/demo/",
    children: [
      { text: "布局", icon: "object-group", link: "layout" },
      { text: "Markdown", icon: "fa6-brands:markdown", link: "markdown" },
      { text: "页面", icon: "file", link: "page" },
      { text: "加密", icon: "lock", link: "encrypt" },
    ],
  },
  { text: "关于", icon: "circle-info", link: "/intro.html" },
]);
