import { navbar } from "vuepress-theme-hope";

export default navbar([
  { text: "首页", icon: "house", link: "/" },
  {
    text: "博文",
    icon: "pen-to-square",
    prefix: "/posts/",
    children: [
      {
        text: "云原生与 K8s",
        icon: "docker",
        prefix: "tech/cloud-native/",
        children: [
          { text: "Kubernetes 核心概念", link: "kubernetes-concepts" },
          { text: "云原生生态全景", link: "cloud-native-cncf" },
          { text: "K8s 生产运维实践", link: "kubernetes-operations" },
          { text: "K8s 版本演进解读", link: "kubernetes-version-evolution" },
          { text: "平台工程", link: "platform-engineering" },
        ],
      },
      {
        text: "数据库",
        icon: "database",
        prefix: "tech/database/",
        children: [
          { text: "PostgreSQL 运维", link: "database-postgresql" },
          { text: "MongoDB 运维", link: "database-mongodb" },
          { text: "MySQL 运维", link: "database-mysql" },
          { text: "国产化数据库全景", link: "database-domestic" },
        ],
      },
      {
        text: "中间件",
        icon: "cubes",
        prefix: "tech/middleware/",
        children: [
          { text: "Redis 运维与排查", link: "middleware-redis" },
          { text: "Kafka 与 ZooKeeper 迁移", link: "middleware-kafka-zookeeper" },
          { text: "etcd 运维与故障排查", link: "middleware-etcd" },
        ],
      },
      {
        text: "存储与分析",
        icon: "chart-column",
        prefix: "tech/storage/",
        children: [
          { text: "MinIO 运维", link: "storage-minio" },
          { text: "ClickHouse 运维", link: "storage-clickhouse" },
        ],
      },
      {
        text: "国产化迁移",
        icon: "flag",
        prefix: "tech/domestic/",
        children: [
          { text: "国产操作系统与软件生态", link: "domestic-os-ecosystem" },
          { text: "国产化迁移实践", link: "domestic-migration-practice" },
          { text: "国产化中间件选型", link: "domestic-middleware" },
          { text: "国产云平台与容器生态", link: "domestic-cloud-platform" },
        ],
      },
      {
        text: "Golang 入门",
        icon: "code",
        prefix: "tech/golang/",
        children: [
          { text: "环境搭建与基础语法", link: "golang-basics" },
          { text: "数据类型与错误处理", link: "golang-datatypes-control" },
          { text: "结构体、方法与接口", link: "golang-struct-interface" },
          { text: "并发编程实战", link: "golang-concurrency" },
          { text: "标准库与项目实战", link: "golang-stdlib-project" },
        ],
      },
      {
        text: "SRE 运维开发",
        icon: "gauge-high",
        prefix: "tech/sre/",
        children: [
          { text: "SLI/SLO/SLA 体系", link: "sre-fundamentals" },
          { text: "CLI 工具开发", link: "sre-go-cli-tools" },
          { text: "Go 操作 K8s", link: "sre-go-kubernetes" },
          { text: "Prometheus Exporter", link: "sre-prometheus-exporter" },
          { text: "故障管理与 Runbook", link: "sre-incident-runbook" },
        ],
      },
      {
        text: "运维监控总览",
        icon: "tower-broadcast",
        prefix: "tech/monitoring/",
        children: [
          { text: "可观测性体系总览", link: "monitoring-observability-overview" },
          { text: "OpenTelemetry 实践", link: "opentelemetry-practice" },
        ],
      },
      {
        text: "Prometheus 生态",
        icon: "fire",
        prefix: "tech/monitoring/prometheus/",
        children: [
          { text: "Prometheus 架构与原理", link: "prometheus-architecture" },
          { text: "PromQL 进阶查询", link: "promql-advanced" },
          { text: "Alertmanager 告警管理", link: "alertmanager-practice" },
          { text: "Prometheus 高可用", link: "prometheus-ha-federation" },
        ],
      },
      {
        text: "VictoriaMetrics",
        icon: "bolt",
        prefix: "tech/monitoring/victoria-metrics/",
        children: [
          { text: "架构与部署", link: "victoria-metrics-architecture" },
          { text: "生产实践", link: "victoria-metrics-production" },
        ],
      },
      {
        text: "Grafana LGTM 栈",
        icon: "chart-line",
        prefix: "tech/monitoring/grafana-stack/",
        children: [
          { text: "Grafana 可视化生态", link: "grafana-ecosystem" },
          { text: "Loki 日志聚合", link: "loki-architecture" },
          { text: "Loki 生产实践", link: "loki-production" },
          { text: "Tempo 分布式追踪", link: "grafana-tempo-tracing" },
        ],
      },
      {
        text: "LLM 评测",
        icon: "chart-bar",
        prefix: "tech/llm/benchmark/",
        children: [
          { text: "评测体系总览", link: "benchmark-overview" },
          { text: "框架对比与选型", link: "benchmark-frameworks-compare" },
          { text: "lm-evaluation-harness", link: "benchmark-lm-eval-harness" },
          { text: "OpenCompass", link: "benchmark-opencompass" },
          { text: "新一代评测基准", link: "benchmark-new-generation" },
          { text: "评测实战指南", link: "benchmark-practice" },
        ],
      },
      {
        text: "模型训练与微调",
        icon: "microchip",
        prefix: "tech/llm/training/",
        children: [
          { text: "本地 GPU 环境搭建", link: "training-local-gpu" },
          { text: "LoRA 微调原理与实践", link: "training-lora-finetune" },
          { text: "SRE 领域模型微调", link: "training-ops-assistant" },
        ],
      },
      {
        text: "其他技术",
        icon: "wrench",
        prefix: "tech/others/",
        children: [
          { text: "VuePress 搭建博客", link: "vuepress-blog" },
          { text: "Cloudflare Pages 部署", link: "cloudflare-deploy" },
          { text: "Git 常用命令", link: "git-commands" },
        ],
      },
      {
        text: "生活",
        icon: "mug-hot",
        prefix: "life/",
        children: [
          { text: "2026 初夏", link: "early-summer-2026" },
          { text: "读书笔记：原则", link: "reading-principles" },
        ],
      },
      {
        text: "笔记",
        icon: "notebook",
        prefix: "notes/",
        children: [
          { text: "Linux 常用技巧", link: "linux-tips" },
        ],
      },
    ],
  },
  {
    text: "AI Wiki",
    icon: "brain",
    prefix: "/posts/wiki/",
    children: [
      {
        text: "概念",
        icon: "lightbulb",
        prefix: "concepts/",
        children: [
          { text: "MCP", link: "model-context-protocol" },
          { text: "Transformer", link: "transformer-architecture" },
          { text: "RAG", link: "retrieval-augmented-generation" },
          { text: "Embedding", link: "embedding" },
          { text: "思维链", link: "chain-of-thought" },
          { text: "Prompt Engineering", link: "prompt-engineering" },
          { text: "Agentic Coding", link: "agentic-coding" },
          { text: "Function Calling", link: "function-calling" },
          { text: "微调", link: "fine-tuning" },
          { text: "Tokenization", link: "tokenization" },
          { text: "向量数据库", link: "vector-database" },
          { text: "知识图谱", link: "knowledge-graph" },
          { text: "注意力机制", link: "attention-mechanism" },
          { text: "语义搜索", link: "semantic-search" },
          { text: "Constitutional AI", link: "constitutional-ai" },
          { text: "LLM 训练流程", link: "llm-training-pipeline" },
        ],
      },
      {
        text: "主题",
        icon: "folder-open",
        prefix: "topics/",
        children: [
          { text: "机器学习", link: "machine-learning" },
          { text: "深度学习", link: "deep-learning" },
          { text: "自然语言处理", link: "natural-language-processing" },
          { text: "计算机视觉", link: "computer-vision" },
          { text: "AI Agents", link: "ai-agents" },
          { text: "软件工程", link: "software-engineering" },
          { text: "DevOps", link: "devops" },
          { text: "Web 开发", link: "web-development" },
          { text: "开源", link: "open-source" },
          { text: "知识管理", link: "knowledge-management" },
        ],
      },
      {
        text: "对比",
        icon: "code-compare",
        prefix: "comparisons/",
        children: [
          { text: "GPT vs Claude vs Gemini", link: "gpt-vs-claude-vs-gemini" },
          { text: "VS Code vs Cursor vs Windsurf", link: "vscode-vs-cursor-vs-windsurf" },
          { text: "Obsidian vs Notion vs Logseq", link: "obsidian-vs-notion-vs-logseq" },
          { text: "RAG vs Compiled Wiki", link: "rag-vs-compiled-wiki" },
          { text: "Python vs JS vs Go", link: "python-vs-javascript-vs-go" },
          { text: "Docker vs Kubernetes", link: "docker-vs-kubernetes" },
        ],
      },
      {
        text: "公司人物",
        icon: "building",
        prefix: "entities/",
        children: [
          { text: "OpenAI", link: "openai" },
          { text: "Anthropic", link: "anthropic" },
          { text: "Google DeepMind", link: "google-deepmind" },
          { text: "Meta AI", link: "meta-ai" },
          { text: "Hugging Face", link: "hugging-face" },
          { text: "Claude", link: "claude" },
          { text: "GPT", link: "gpt" },
          { text: "Cursor", link: "cursor" },
          { text: "GitHub Copilot", link: "github-copilot" },
          { text: "Ollama", link: "ollama" },
          { text: "Perplexity", link: "perplexity" },
          { text: "Vercel", link: "vercel" },
          { text: "Obsidian", link: "obsidian" },
          { text: "Sam Altman", link: "sam-altman" },
          { text: "Andrej Karpathy", link: "andrej-karpathy" },
        ],
      },
      {
        text: "指南",
        icon: "book-open",
        prefix: "guides/",
        children: [
          { text: "构建 RAG 系统", link: "how-to-build-rag-system" },
          { text: "微调 LLM", link: "how-to-fine-tune-llm" },
          { text: "构建 AI Agent", link: "how-to-build-ai-agent" },
          { text: "写好 Prompt", link: "how-to-write-effective-prompts" },
          { text: "使用 Obsidian", link: "how-to-use-obsidian" },
          { text: "升级 Dify RAG", link: "how-to-upgrade-dify-rag-workflow" },
          { text: "构建 LLM Wiki", link: "how-to-build-llm-wiki" },
        ],
      },
      {
        text: "综合分析",
        icon: "chart-line",
        prefix: "synthesis/",
        children: [
          { text: "2026 AI 状态", link: "state-of-ai-2026" },
          { text: "LLM 演进", link: "evolution-of-llm" },
          { text: "编程的未来", link: "future-of-programming" },
          { text: "AI 安全全景", link: "ai-safety-landscape" },
          { text: "LLM 应用模式", link: "llm-application-patterns" },
          { text: "开源 AI 生态", link: "open-source-ai-ecosystem" },
        ],
      },
    ],
  },
  {
    text: "功能演示",
    icon: "laptop-code",
    prefix: "/demo/",
    children: [
      { text: "布局", icon: "object-group", link: "layout" },
      { text: "Markdown", icon: "fa6-brands:markdown", link: "markdown" },
      { text: "页面", icon: "file", link: "page" },
      { text: "加密", icon: "lock", link: "encrypt" },
    ],
  },
  { text: "关于", icon: "circle-info", link: "/intro.html" },
]);
