import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/": [
    "",
    {
      text: "功能演示",
      icon: "laptop-code",
      prefix: "demo/",
      link: "demo/",
      children: "structure",
    },
    {
      text: "云原生与 K8s",
      icon: "docker",
      prefix: "posts/tech/",
      collapsible: true,
      children: [
        "kubernetes-concepts",
        "cloud-native-cncf",
        "kubernetes-operations",
        "kubernetes-version-evolution",
        "platform-engineering",
      ],
    },
    {
      text: "数据库",
      icon: "database",
      prefix: "posts/tech/",
      collapsible: true,
      children: [
        "database-postgresql-mongodb",
      ],
    },
    {
      text: "中间件",
      icon: "cubes",
      prefix: "posts/tech/",
      collapsible: true,
      children: [
        "middleware-redis",
        "middleware-kafka-zookeeper",
        "middleware-etcd",
      ],
    },
    {
      text: "存储与分析",
      icon: "chart-column",
      prefix: "posts/tech/",
      collapsible: true,
      children: [
        "storage-minio-clickhouse",
      ],
    },
    {
      text: "Golang 入门",
      icon: "code",
      prefix: "posts/tech/",
      collapsible: true,
      children: [
        "golang-basics",
        "golang-datatypes-control",
        "golang-struct-interface",
        "golang-concurrency",
        "golang-stdlib-project",
      ],
    },
    {
      text: "SRE 运维开发",
      icon: "gauge-high",
      prefix: "posts/tech/",
      collapsible: true,
      children: [
        "sre-fundamentals",
        "sre-go-cli-tools",
        "sre-go-kubernetes",
        "sre-prometheus-exporter",
        "sre-incident-runbook",
      ],
    },
    {
      text: "LLM 评测",
      icon: "chart-bar",
      prefix: "posts/tech/",
      collapsible: true,
      children: [
        "benchmark-overview",
        "benchmark-lm-eval-harness",
        "benchmark-opencompass",
        "benchmark-new-generation",
        "benchmark-practice",
        "benchmark-frameworks-compare",
      ],
    },
    {
      text: "模型训练与微调",
      icon: "microchip",
      prefix: "posts/tech/",
      collapsible: true,
      children: [
        "training-local-gpu",
        "training-lora-finetune",
        "training-ops-assistant",
      ],
    },
    {
      text: "其他技术文章",
      icon: "wrench",
      prefix: "posts/tech/",
      collapsible: true,
      children: [
        "vuepress-blog",
        "cloudflare-deploy",
        "git-commands",
      ],
    },
    {
      text: "生活",
      icon: "mug-hot",
      prefix: "posts/life/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "笔记",
      icon: "notebook",
      prefix: "posts/notes/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "AI Wiki",
      icon: "brain",
      prefix: "posts/wiki/",
      collapsible: true,
      children: [
        {
          text: "概念",
          icon: "lightbulb",
          prefix: "concepts/",
          children: "structure",
        },
        {
          text: "主题",
          icon: "folder-open",
          prefix: "topics/",
          children: "structure",
        },
        {
          text: "对比",
          icon: "code-compare",
          prefix: "comparisons/",
          children: "structure",
        },
        {
          text: "公司人物",
          icon: "building",
          prefix: "entities/",
          children: "structure",
        },
        {
          text: "指南",
          icon: "book-open",
          prefix: "guides/",
          children: "structure",
        },
        {
          text: "综合分析",
          icon: "chart-line",
          prefix: "synthesis/",
          children: "structure",
        },
      ],
    },
    "intro",
  ],
});
