import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/": [
    "",
    {
      text: "功能演示",
      icon: "laptop-code",
      prefix: "demo/",
      link: "demo/",
      children: "structure",
    },
    {
      text: "云原生与 K8s",
      icon: "docker",
      prefix: "posts/tech/cloud-native/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "数据库",
      icon: "database",
      prefix: "posts/tech/database/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "中间件",
      icon: "cubes",
      prefix: "posts/tech/middleware/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "存储与分析",
      icon: "chart-column",
      prefix: "posts/tech/storage/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "国产化迁移",
      icon: "flag",
      prefix: "posts/tech/domestic/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Golang 入门",
      icon: "code",
      prefix: "posts/tech/golang/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "SRE 运维开发",
      icon: "gauge-high",
      prefix: "posts/tech/sre/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "运维监控告警",
      icon: "tower-broadcast",
      prefix: "posts/tech/monitoring/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "LLM 评测与训练",
      icon: "chart-bar",
      prefix: "posts/tech/llm/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "其他技术文章",
      icon: "wrench",
      prefix: "posts/tech/others/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "生活",
      icon: "mug-hot",
      prefix: "posts/life/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "笔记",
      icon: "notebook",
      prefix: "posts/notes/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "AI Wiki",
      icon: "brain",
      prefix: "posts/wiki/",
      collapsible: true,
      children: [
        {
          text: "概念",
          icon: "lightbulb",
          prefix: "concepts/",
          children: "structure",
        },
        {
          text: "主题",
          icon: "folder-open",
          prefix: "topics/",
          children: "structure",
        },
        {
          text: "对比",
          icon: "code-compare",
          prefix: "comparisons/",
          children: "structure",
        },
        {
          text: "公司人物",
          icon: "building",
          prefix: "entities/",
          children: "structure",
        },
        {
          text: "指南",
          icon: "book-open",
          prefix: "guides/",
          children: "structure",
        },
        {
          text: "综合分析",
          icon: "chart-line",
          prefix: "synthesis/",
          children: "structure",
        },
      ],
    },
    "intro",
  ],
});
